### ISSUE TITLE
TypeError: can't pickle instancemethod objects 

### ISSUE THREAD

**Issue by liubenyuan** [NGSolve/ngsgui#1]
Hi, I install ngsgui using the git version, and `ngsgui`, `spyder_ngsgui` are in the PYTHONPATH, I also copied `spyder_ngsgui` into `~/.config/spyder-py3` folder.

However, when I run the demo, i.e., `example.py` of ngsgui in spyder-4.0, it yield an error:
```python
task-based parallelization (C++11 threads) using 4 threads
task-based parallelization (C++11 threads) using 4 threads
Store pointer of type ngfem::CoefficientFunction
Typeids are different: ngfem::CoefficientFunction vs ngfem::CoordCoefficientFunction
Didn't find pointer, create new registry entry at 0
Store a possibly more complicated pointer
Writeout version needed = 
Pickling output for object of type ngfem::CoefficientFunction = ([b'\xfd\xff\xff\xff\x1f\x00\x00\x00ngfem::CoordCoefficientFunction\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', b'\x00\x00\x00\x00\x00\x00\x00\x00', b'\x00\x00\x00\x00\x00\x00\x00\x00'],)
Traceback (most recent call last):

  File "/home/postgres/cem/github/ngsgui/demo/example.py", line 43, in <module>
    s = Draw(x, mesh, 'lk')

  File "/home/postgres/python/lib/spyder_ngsgui/startup.py", line 31, in Draw
    handler.ngsolve_draw(index, *args, **kwargs)

  File "/usr/share/miniconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 542, in __call__
    call_dict, call_data, self._comm_id)

  File "/usr/share/miniconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 397, in _get_call_return_value
    comm_id=comm_id)

  File "/usr/share/miniconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 245, in _send_message
    data, protocol=self._comms[comm_id]['pickle_protocol'])]

  File "/usr/share/miniconda3/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 1125, in dumps
    cp.dump(obj)

  File "/usr/share/miniconda3/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 482, in dump
    return Pickler.dump(self, obj)

  File "/usr/share/miniconda3/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)

  File "/usr/share/miniconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self

  File "/usr/share/miniconda3/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())

  File "/usr/share/miniconda3/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)

  File "/usr/share/miniconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self

  File "/usr/share/miniconda3/lib/python3.7/pickle.py", line 789, in save_tuple
    save(element)

  File "/usr/share/miniconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)

  File "/usr/share/miniconda3/lib/python3.7/pickle.py", line 633, in save_reduce
    save(cls)

  File "/usr/share/miniconda3/lib/python3.7/pickle.py", line 518, in save
    self.save_global(obj)

  File "/usr/share/miniconda3/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 877, in save_global
    self.save_dynamic_class(obj)

  File "/usr/share/miniconda3/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 686, in save_dynamic_class
    save(clsdict)

  File "/usr/share/miniconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self

  File "/usr/share/miniconda3/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())

  File "/usr/share/miniconda3/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)

  File "/usr/share/miniconda3/lib/python3.7/pickle.py", line 524, in save
    rv = reduce(self.proto)

TypeError: can't pickle instancemethod objects
```

**Comment by ChrLackner** [comment]
Hi, this is due to some new changes in cloudpickle which I haven't yet looked into. Did you install via pip? Then I would have thought that it would resolve the dependency cloudpickle<1.2.
Just install cloudpickle v.1.1 via pip, this should resolve the issue.
If you have an idea about how to fix it or it doesn't fix the problem please reopen this issue.

The examples in the demo folder may be outdated or may not work correctly with spyder yet. I've tested the spyder interface only with the ngsolve py_tutorials poisson.py and navierstokes.py to be honest... If you run into troubles let me know.
Thanks and best,
Christopher

**Comment by liubenyuan** [comment]
I install via github directly, which is simply `python setup.py build` and then copy `ngsgui`, `spyder_ngsgui` into python paths, also copy `spyder_ngsgui` into `~/.spyder-py3/plugins/`. I will check if this works.

**Comment by liubenyuan** [comment]
Thanks, install `cloudpickle=1.1.1` fixed this problem.
