### ISSUE TITLE
update to use Pyside 5.14?

### ISSUE THREAD

**Issue by ddrake** [NGSolve/ngsgui#3]
Hi,  I'm able to use the ngsgui on Ubuntu 20.04 with Python3.8.3, but on MacOS (high sierra) with Python3.8.3 I get the message "TypeError: 'Shiboken.ObjectType' object is not iterable".   This occurs when any script is run with the new gui.  For example:

$ ngsolve poisson.py
importing NGSolve-6.2.2006-30-gaf29b503
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/ngsolve", line 11, in <module>
    load_entry_point('ngsgui==0.1.11', 'console_scripts', 'ngsolve')()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ngsgui/__init__.py", line 18, in <module>
    from .scenes import *
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ngsgui/scenes.py", line 5, in <module>
    from . import widgets as wid
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ngsgui/widgets.py", line 6, in <module>
    from .thread import inmain_decorator
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ngsgui/thread.py", line 105, in <module>
    class Caller(QObject):
TypeError: 'Shiboken.ObjectType' object is not iterable

There are many reports of this sort of error with older versions of QT and Python 3.8.  In particular, [this link](https://youtrack.jetbrains.com/issue/PY-39321) gives an example that shows how this error can be produced by deriving more than one class from QWidget.  I was able to produce the error by doing just that.  It mentions that the issue is supposedly fixed in Pyside 5.14.0, i.e. that there is a workaround in Pyside 5.14.0 so that it should work with Python 3.8

I was wondering if it might make sense to update the setup project for ngsgui to use this newer version of Pyside?  Or if we need the ngsgui on Mac OS, do you suggest that we downgrade to Python 3.7?

Best,
Dow

**Comment by ChrLackner** [comment]
fixed in https://github.com/NGSolve/ngsgui/commit/a68a75315f1963e5eb9fa11c1c14614ee3c08d4e
thanks

**Comment by ddrake** [comment]
Thanks, Christopher!
